#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <syslog.h>
#include <string.h>
#include <errno.h>
#include <curl/curl.h>
#include <sys/stat.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include "glib-object.h"
#include "json-glib.h"
#include "misc.h"
